import { StyleSheet } from 'react-native';

import { MOBILE_SAGE_NEUTRALS, MOBILE_SAGE_SHADOWS, MOBILE_SAGE_SLATE } from '../mobile-theme';
import { ADMIN_PAGE_EDGE_PADDING } from './adminConfig';

export const styles = StyleSheet.create({
  actionButton: {
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    flexBasis: '47%',
    flexDirection: 'row',
    gap: 7,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '900',
  },
  actionList: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
  },
  actionRow: {
    alignItems: 'center',
    borderBottomColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 54,
    paddingHorizontal: 13,
  },
  actionRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  actionRowMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 11,
    fontWeight: '800',
  },
  actionRowTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 13,
    fontWeight: '900',
  },
  activeTab: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.controlActive,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
  },
  badge: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderRadius: 999,
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  autoScanSwitch: {
    alignItems: 'center',
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 4,
    minHeight: 32,
    minWidth: 88,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  autoScanSwitchOff: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
  },
  autoScanSwitchText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  card: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 9,
    padding: 14,
  },
  cardGroup: {
    gap: 11,
  },
  cardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  cardMeta: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  cardSubtitle: {
    color: MOBILE_SAGE_SLATE.muted,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: '700',
  },
  cardTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 15,
    fontWeight: '900',
  },
  cardTitleWrap: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  activeTaskCard: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 15,
    borderWidth: 1,
    gap: 12,
    padding: 12,
  },
  activeTaskFolder: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  activeTaskFolderLabel: {
    color: MOBILE_SAGE_SLATE.strong,
    fontWeight: '900',
  },
  activeTaskHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  activeTaskProgressBadge: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    flexShrink: 0,
    minHeight: 30,
    minWidth: 58,
    justifyContent: 'center',
    paddingHorizontal: 9,
  },
  activeTaskProgressBadgeText: {
    fontSize: 12,
    fontWeight: '900',
  },
  activeTaskProgressBlock: {
    gap: 8,
  },
  activeTaskProgressMeta: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  activeTaskSectionLabel: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 14,
    fontWeight: '900',
  },
  activeTaskList: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    padding: 8,
  },
  activeTaskSubTaskText: {
    color: MOBILE_SAGE_SLATE.muted,
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  activeTaskTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 16,
    fontWeight: '900',
  },
  activeTaskTitleWrap: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  activeTaskCode: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: '900',
  },
  activeTaskCountPill: {
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    color: MOBILE_SAGE_SLATE.muted,
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderRadius: 999,
    borderWidth: 1,
    fontSize: 11,
    fontWeight: '900',
  },
  activeTaskPercentText: {
    color: MOBILE_SAGE_SLATE.subtle,
    flexShrink: 0,
    fontSize: 12,
    fontWeight: '900',
  },
  activeTaskSummaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  progressFill: {
    borderRadius: 999,
    height: '100%',
  },
  progressTrack: {
    borderRadius: 999,
    height: 8,
    overflow: 'hidden',
  },
  taskInfoCard: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    gap: 12,
  },
  taskInfoHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  taskInfoIcon: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  threadControl: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  threadInput: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 12,
    borderWidth: 1,
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 15,
    fontWeight: '900',
    minHeight: 42,
    minWidth: 68,
    paddingHorizontal: 10,
    textAlign: 'center',
  },
  threadStepButton: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 12,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  maintenanceTaskList: {
    gap: 6,
    padding: 8,
  },
  maintenanceTaskCode: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: '900',
  },
  maintenanceTaskCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  maintenanceTaskRow: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  maintenanceTaskRowActive: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.controlActive,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
  },
  maintenanceTaskText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
  },
  maintenanceDropdownTrigger: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  maintenanceSheet: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    gap: 12,
    maxHeight: '82%',
    padding: 14,
  },
  cacheClearButton: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    minHeight: 30,
    flexShrink: 0,
    paddingHorizontal: 9,
  },
  cacheClearText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  cacheDetailCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  cacheDetailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  cacheDetailIcon: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderRadius: 999,
    borderWidth: 1,
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
  cacheDetailLabel: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 11,
    fontWeight: '900',
  },
  cacheDetailMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 9,
    fontWeight: '800',
  },
  cacheDetailStat: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    width: '48%',
    flexGrow: 1,
    gap: 6,
    minHeight: 46,
    padding: 8,
  },
  cacheDetailValue: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 14,
    fontWeight: '900',
    maxWidth: 76,
  },
  cacheCompositionRow: {
    borderTopColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderTopWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    paddingTop: 10,
  },
  cacheFolderSection: {
    gap: 9,
  },
  cacheFolderCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  cacheFolderIcon: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  cacheFolderName: {
    color: MOBILE_SAGE_SLATE.strong,
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '900',
  },
  cacheFolderNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  cacheFolderPath: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 11,
    fontWeight: '700',
  },
  cacheFolderSummary: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  cacheFolderRow: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 15,
    borderWidth: 1,
    gap: 10,
    padding: 10,
  },
  cacheFolderRowHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
  },
  cacheFolderTitle: {
    alignItems: 'flex-start',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  cacheHeroActions: {
    flexWrap: 'wrap',
    flexDirection: 'row',
    gap: 8,
  },
  cacheHeroCard: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  cacheHeroCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  cacheHeroFooter: {
    borderTopColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderTopWidth: 1,
    gap: 8,
    paddingTop: 10,
  },
  cacheHeroHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  cacheHeroIcon: {
    alignItems: 'center',
    borderRadius: 14,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  cacheHeroKicker: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: '900',
  },
  cacheHeroMeta: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: '800',
    lineHeight: 16,
  },
  cacheHeroStat: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  cacheHeroStatLabel: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: '900',
  },
  cacheHeroStatMeta: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  cacheHeroStats: {
    borderTopColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingTop: 10,
  },
  cacheHeroStatValue: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 18,
    fontWeight: '900',
  },
  cacheHeroSubtitle: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  cacheHeroTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 18,
    fontWeight: '900',
  },
  cacheList: {
    gap: 8,
  },
  cacheMetaPill: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  cacheMetaPillText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 10,
    fontWeight: '900',
  },
  cacheMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
  },
  cacheSectionHeader: {
    alignItems: 'baseline',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'space-between',
  },
  cacheSectionMeta: {
    color: MOBILE_SAGE_SLATE.muted,
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '800',
  },
  cacheSectionTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 14,
    fontWeight: '900',
  },
  cacheState: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    minHeight: 96,
    justifyContent: 'center',
    padding: 14,
  },
  cacheTreeChildren: {
    gap: 8,
    marginTop: 8,
  },
  cacheTreeNode: {
    gap: 0,
  },
  cacheTreeToggle: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  cacheStatusDot: {
    backgroundColor: MOBILE_SAGE_SLATE.subtle,
    borderRadius: 999,
    height: 7,
    width: 7,
  },
  cacheStatusSwitch: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 32,
    paddingHorizontal: 10,
  },
  cacheStatusSwitchText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 11,
    fontWeight: '900',
  },
  checkGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  checkTile: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    flexBasis: '48%',
    flexDirection: 'row',
    flexGrow: 1,
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 10,
  },
  checkTileCopy: {
    flex: 1,
    minWidth: 0,
  },
  checkTileMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: '800',
  },
  checkTileText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 12,
    fontWeight: '900',
  },
  confirmSheet: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderRadius: 20,
    marginHorizontal: 18,
    paddingTop: 16,
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  content: {
    alignItems: 'stretch',
    gap: 12,
    paddingBottom: 130,
    paddingHorizontal: ADMIN_PAGE_EDGE_PADDING,
    width: '100%',
  },
  dangerSoftButton: {
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
  },
  deletedLogActions: {
    flexDirection: 'row',
    gap: 10,
  },
  deletedFilesCompactPanel: {
    backgroundColor: '#fff7f7',
    borderColor: '#fee2e2',
    borderRadius: 14,
    borderWidth: 1,
    gap: 5,
    padding: 7,
  },
  deletedFilesActionButton: {
    alignItems: 'center',
    borderRadius: 9,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'center',
    minHeight: 26,
    minWidth: 58,
    paddingHorizontal: 8,
  },
  deletedFilesActionGrid: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
  },
  deletedFilesActionText: {
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '900',
  },
  deletedFilesCountLabel: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: '900',
  },
  deletedFilesCountPill: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: '#fee2e2',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 4,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  deletedFilesCountValue: {
    color: '#b91c1c',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 18,
  },
  deletedFilesDangerButton: {
    backgroundColor: '#fff1f2',
    borderColor: '#fecdd3',
  },
  deletedFilesDateRail: {
    ...MOBILE_SAGE_SHADOWS.panel,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.96)',
    borderColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderRadius: 16,
    borderWidth: 1,
    bottom: 10,
    justifyContent: 'center',
    overflow: 'hidden',
    paddingVertical: 4,
    position: 'absolute',
    right: 8,
    top: 10,
    width: 54,
  },
  deletedFilesDateRailContent: {
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 4,
    paddingVertical: 6,
    width: '100%',
  },
  deletedFilesDateRailScroller: {
    flex: 1,
    overflow: 'hidden',
    width: '100%',
  },
  deletedFilesDateRailDot: {
    backgroundColor: '#fecaca',
    borderRadius: 999,
    flexShrink: 0,
    height: 4,
    width: 4,
  },
  deletedFilesDateRailGroup: {
    alignItems: 'center',
    gap: 4,
    width: '100%',
  },
  deletedFilesDateRailItem: {
    alignItems: 'center',
    borderRadius: 11,
    flexDirection: 'row',
    gap: 2,
    justifyContent: 'center',
    minHeight: 28,
    minWidth: 0,
    paddingHorizontal: 2,
    paddingVertical: 3,
    width: '100%',
  },
  deletedFilesDateRailLabel: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 9,
    flexShrink: 1,
    fontWeight: '900',
    lineHeight: 11,
    maxWidth: '100%',
    minWidth: 0,
    textAlign: 'center',
  },
  deletedFilesDateRailYear: {
    color: MOBILE_SAGE_SLATE.body,
    flexShrink: 1,
    fontSize: 10,
    fontWeight: '900',
    lineHeight: 12,
    maxWidth: '100%',
    minWidth: 0,
    textAlign: 'center',
  },
  deletedFilesDateRailYearButton: {
    alignItems: 'center',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 2,
    justifyContent: 'center',
    minHeight: 30,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 2,
    paddingVertical: 3,
    width: '100%',
  },
  deletedFilesDateRailYearButtonExpanded: {
    backgroundColor: '#fff1f2',
  },
  deletedFilesError: {
    backgroundColor: '#fff1f2',
    borderColor: '#fecaca',
    borderRadius: 14,
    borderWidth: 1,
    color: '#b91c1c',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
    padding: 11,
    textAlign: 'center',
  },
  deletedFilesHelp: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 15,
    borderWidth: 1,
    gap: 8,
    padding: 12,
  },
  deletedFilesSheet: {
    flex: 0,
    gap: 7,
    maxHeight: '90%',
  },
  deletedFilesStateText: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 12,
    fontWeight: '800',
    padding: 11,
    textAlign: 'center',
  },
  deletedFilesSummaryCard: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  deletedFilesSummaryCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  deletedFilesSummaryIcon: {
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  deletedFilesSummaryMeta: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 14,
  },
  deletedFilesSummaryTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 12,
    fontWeight: '900',
  },
  deletedFilesGroupHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
    paddingHorizontal: 4,
    paddingVertical: 8,
  },
  deletedFilesGroupCount: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    color: MOBILE_SAGE_SLATE.muted,
    flexShrink: 0,
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  deletedFilesGroupDate: {
    color: MOBILE_SAGE_SLATE.body,
    flex: 1,
    fontSize: 12,
    fontWeight: '900',
  },
  deletedFilesGroupMark: {
    backgroundColor: '#fecaca',
    borderRadius: 999,
    height: 22,
    width: 4,
  },
  deletedFilesVirtualContent: {
    padding: 8,
    paddingBottom: 14,
  },
  deletedFilesVirtualContentWithRail: {
    paddingRight: 72,
  },
  deletedFilesVirtualFrame: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 16,
    borderWidth: 1,
    flexGrow: 0,
    flexShrink: 0,
    overflow: 'hidden',
  },
  deletedFilesVirtualList: {
    flex: 1,
  },
  deletedFileMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 11,
    fontWeight: '800',
  },
  deletedFileName: {
    color: MOBILE_SAGE_SLATE.strong,
    flex: 1,
    fontSize: 13,
    fontWeight: '900',
  },
  deletedFileNameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    minWidth: 0,
  },
  deletedFilePath: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  deletedFileRow: {
    borderTopColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderTopWidth: 1,
    gap: 5,
    paddingTop: 9,
  },
  deletedFileVirtualRow: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderRadius: 14,
    borderWidth: 1,
    gap: 5,
    marginBottom: 8,
    padding: 10,
  },
  dialogActions: {
    flexDirection: 'row',
    gap: 10,
  },
  dialogPrimaryButton: {
    alignItems: 'center',
    borderRadius: 14,
    flex: 1,
    height: 44,
    justifyContent: 'center',
  },
  dialogPrimaryText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '900',
  },
  dialogSecondaryButton: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    height: 44,
    justifyContent: 'center',
  },
  dialogSecondaryText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 13,
    fontWeight: '900',
  },
  dirBar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  dirBrowser: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    gap: 7,
    padding: 8,
  },
  dirMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    minWidth: 0,
  },
  dirName: {
    color: MOBILE_SAGE_SLATE.body,
    flex: 1,
    fontSize: 12,
    fontWeight: '900',
  },
  dirPath: {
    color: MOBILE_SAGE_SLATE.muted,
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
  },
  dirRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    minHeight: 34,
  },
  disabledButton: {
    opacity: 0.5,
  },
  editorContent: {
    gap: 12,
    paddingBottom: 14,
  },
  editorSection: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    padding: 10,
  },
  editorSectionTitle: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  editorSheet: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    flex: 1,
    gap: 12,
    marginTop: 42,
    padding: 14,
  },
  editorSmallButton: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 12,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 42,
  },
  emptyText: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 13,
    fontWeight: '800',
    paddingVertical: 12,
    textAlign: 'center',
  },
  error: {
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
    borderRadius: 14,
    borderWidth: 1,
    color: '#b91c1c',
    fontSize: 13,
    fontWeight: '800',
    marginHorizontal: ADMIN_PAGE_EDGE_PADDING,
    padding: 12,
  },
  folderChip: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    maxWidth: '100%',
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  folderChipText: {
    color: MOBILE_SAGE_SLATE.body,
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '900',
  },
  folderChips: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  folderInputRow: {
    flexDirection: 'row',
    gap: 8,
  },
  formField: {
    flex: 1,
    gap: 6,
  },
  formGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  formLabel: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  galleryActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    paddingTop: 3,
  },
  galleryAddButton: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    minHeight: 34,
    paddingHorizontal: 11,
  },
  galleryAddButtonText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 12,
    fontWeight: '900',
  },
  galleryCommandButton: {
    alignItems: 'center',
    borderRadius: 13,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 38,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  galleryCommandButtonText: {
    fontSize: 12,
    fontWeight: '900',
  },
  galleryCommandCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  galleryCommandHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
  },
  galleryCommandIcon: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  galleryCommandMeta: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  galleryCommandPanel: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  galleryCommandTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 15,
    fontWeight: '900',
  },
  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: 8,
    justifyContent: 'space-between',
  },
  galleryListHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 2,
  },
  galleryListMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 11,
    fontWeight: '800',
  },
  galleryListTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 14,
    fontWeight: '900',
  },
  galleryMetricLabel: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: '800',
  },
  galleryMetricPill: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 13,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    minHeight: 48,
    justifyContent: 'center',
  },
  galleryMetricRow: {
    flexDirection: 'row',
    gap: 7,
  },
  galleryMetricValue: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 15,
    fontWeight: '900',
  },
  galleryStatsCard: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderRadius: 13,
    borderWidth: 1,
    gap: 8,
    overflow: 'hidden',
    padding: 9,
  },
  galleryStatsCardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  galleryStatsHero: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 13,
    borderWidth: 1,
    gap: 7,
    padding: 8,
  },
  galleryStatsHeroCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  galleryStatsHeroHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  galleryStatsHeroIcon: {
    alignItems: 'center',
    borderRadius: 11,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  galleryStatsHeroMeta: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  galleryStatsHeroTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 13,
    fontWeight: '900',
  },
  galleryStatsInlineMetrics: {
    flexDirection: 'row',
    gap: 6,
  },
  galleryStatsInlineLabel: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: '900',
  },
  galleryStatsInlineMetric: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    justifyContent: 'center',
    minHeight: 42,
    minWidth: 0,
    paddingHorizontal: 7,
    paddingVertical: 6,
  },
  galleryStatsInlineValue: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 13,
    fontWeight: '900',
  },
  galleryStatsList: {
    gap: 8,
    padding: 8,
    paddingBottom: 14,
  },
  galleryStatsListFrame: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  galleryStatsListScroll: {
    flex: 1,
  },
  galleryStatsMetric: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderRadius: 10,
    borderWidth: 1,
    flexBasis: '47%',
    flexGrow: 1,
    gap: 1,
    justifyContent: 'center',
    minHeight: 42,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  galleryStatsMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  galleryStatsMetricLabel: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 9,
    fontWeight: '900',
  },
  galleryStatsMetricValue: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 15,
    fontWeight: '900',
  },
  galleryStatsRefreshButton: {
    borderRadius: 11,
    height: 32,
    width: 36,
  },
  galleryStatsSection: {
    flex: 1,
    gap: 9,
    minHeight: 0,
  },
  galleryStatsSectionHeader: {
    alignItems: 'baseline',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 2,
  },
  galleryPrimaryActions: {
    flexDirection: 'row',
    gap: 7,
  },
  gallerySecondaryActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  iconCloseButton: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  infoItem: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 5,
    padding: 11,
  },
  infoLabel: {
    color: MOBILE_SAGE_SLATE.muted,
    flex: 0.42,
    fontSize: 12,
    fontWeight: '800',
  },
  infoRow: {
    borderTopColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingTop: 8,
  },
  infoValue: {
    color: MOBILE_SAGE_SLATE.strong,
    flex: 0.58,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  languageChip: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 34,
    paddingHorizontal: 12,
  },
  languageChipActive: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.controlActive,
  },
  languageChipText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  languageChipTextActive: {
    color: MOBILE_SAGE_SLATE.strong,
  },
  languageRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  systemConfigGrid: {
    gap: 8,
  },
  systemConfigTile: {
    alignItems: 'flex-start',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  systemConfigTileTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 13,
    fontWeight: '900',
  },
  systemConfigTileValue: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 11,
    fontWeight: '800',
  },
  systemLogLevel: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    width: 58,
  },
  systemLogMessage: {
    color: MOBILE_SAGE_SLATE.body,
    flex: 1,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 17,
  },
  systemLogRow: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.borderSoft,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    padding: 10,
  },
  input: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 13,
    fontWeight: '800',
    minHeight: 42,
    paddingHorizontal: 12,
  },
  loadingMetricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  loadingStack: {
    gap: 10,
  },
  metric: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 15,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 4,
    padding: 12,
  },
  metricLabel: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  metricMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: '800',
  },
  metricValue: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 17,
    fontWeight: '900',
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  modalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  modalOverlay: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.sheetOverlay,
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalSubtitle: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  modalTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 18,
    fontWeight: '900',
  },
  modalTitleWrap: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  weightModalOverlay: {
    justifyContent: 'center',
  },
  weightSheet: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderRadius: 22,
    flexShrink: 0,
    marginHorizontal: 18,
    paddingTop: 16,
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  weightSheetHeader: {},
  notificationLayer: {
    alignItems: 'center',
    left: ADMIN_PAGE_EDGE_PADDING,
    position: 'absolute',
    right: ADMIN_PAGE_EDGE_PADDING,
    top: 66,
    zIndex: 20,
  },
  notificationText: {
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '900',
  },
  notificationToast: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    maxWidth: '100%',
    minHeight: 40,
    paddingHorizontal: 14,
  },
  queueActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sectionIntro: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 12,
  },
  sectionIntroCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  sectionIntroIcon: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderRadius: 14,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  sectionIntroMeta: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  sectionIntroTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 15,
    fontWeight: '900',
  },
  screen: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.pageBg,
    flex: 1,
    gap: 10,
    paddingTop: 10,
  },
  scanListEditor: {
    gap: 9,
  },
  skeletonCard: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 9,
    minHeight: 92,
    padding: 14,
  },
  skeletonCardLine: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderRadius: 999,
    height: 10,
    opacity: 0.84,
    width: '82%',
  },
  skeletonCardLineShort: {
    width: '56%',
  },
  skeletonCardTitle: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.controlActive,
    borderRadius: 999,
    height: 14,
    width: '44%',
  },
  skeletonLabel: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderRadius: 999,
    height: 10,
    width: '58%',
  },
  skeletonMetric: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 15,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 9,
    minHeight: 76,
    padding: 12,
  },
  skeletonValue: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.controlActive,
    borderRadius: 999,
    height: 18,
    width: '72%',
  },
  smallAction: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    minHeight: 30,
    paddingHorizontal: 8,
  },
  smallActionDanger: {
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
  },
  smallActionText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  smallActionTextDanger: {
    color: '#b91c1c',
  },
  statsContent: {
    flex: 1,
    gap: 9,
    minHeight: 0,
  },
  statsSheet: {
    flex: 1,
    gap: 8,
    maxHeight: '88%',
    padding: 10,
  },
  statusTab: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  statusTabText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  statusTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  summaryPill: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 11,
    fontWeight: '900',
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  summaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  tab: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 48,
    minWidth: 128,
    paddingHorizontal: 11,
  },
  tabCopy: {
    flex: 1,
    minWidth: 0,
  },
  tabDescription: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: '800',
  },
  tabRail: {
    gap: 7,
    paddingHorizontal: ADMIN_PAGE_EDGE_PADDING,
  },
  tabRailFrame: {
    marginHorizontal: 0,
  },
  tabText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 12,
    fontWeight: '900',
  },
  userAvatar: {
    alignItems: 'center',
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderRadius: 999,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
});
