import { app, BrowserWindow, ipcMain, shell } from 'electron';
import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

let mainWindow: BrowserWindow | undefined;

const WEB_DEV_SERVER_URL = process.env.KWPHOTO_WEB_DEV_SERVER_URL;

interface CacheRecord {
  blobFileName?: string;
  folderScopeKey?: string;
  hasBlob?: boolean;
  key: string;
  scope?: string;
  [key: string]: unknown;
}

interface CacheIndex {
  records: CacheRecord[];
}

interface CacheBlobFile {
  fileName: string;
  size: number;
}

/**
 * Creates the main application window and attaches the hardened preload bridge.
 */
const createMainWindow = async (): Promise<void> => {
  mainWindow = new BrowserWindow({
    backgroundColor: '#f7f8f4',
    height: 820,
    minHeight: 680,
    minWidth: 1080,
    show: false,
    title: 'KW Photo',
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: getPreloadPath(),
      sandbox: false,
    },
    width: 1280,
  });

  mainWindow.once('ready-to-show', () => {
    mainWindow?.show();
  });

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    void shell.openExternal(url);
    return { action: 'deny' };
  });

  if (WEB_DEV_SERVER_URL) {
    await mainWindow.loadURL(WEB_DEV_SERVER_URL);
    mainWindow.webContents.openDevTools({ mode: 'detach' });
    return;
  }

  await mainWindow.loadFile(getRendererIndexPath());
};

/**
 * Resolves the preload script from the packaged app root.
 */
const getPreloadPath = (): string => {
  return path.join(app.getAppPath(), 'dist', 'preload', 'preload.cjs');
};

/**
 * Resolves the Web renderer generated by @kwphoto/web.
 */
const getRendererIndexPath = (): string => {
  return path.join(app.getAppPath(), 'dist', 'renderer', 'index.html');
};

/**
 * Registers the narrow desktop bridge exposed to the renderer.
 */
const registerIpcHandlers = (): void => {
  ipcMain.handle('kwphoto:desktop:get-runtime-info', () => {
    return {
      platform: process.platform,
      versions: {
        chrome: process.versions.chrome,
        electron: process.versions.electron,
        node: process.versions.node,
      },
    };
  });
  ipcMain.handle('kwphoto:cache:storage-info', getCacheStorageInfo);
  ipcMain.handle('kwphoto:cache:fetch-media', (_event, params: { url: string }) => fetchMediaBytes(params.url));
  ipcMain.handle('kwphoto:cache:read-record', (_event, params: { key: string }) => readCacheRecord(params.key));
  ipcMain.handle('kwphoto:cache:write-record', (
    _event,
    params: { blobBytes: number[] | null; record: CacheRecord },
  ) => writeCacheRecord(params.record, params.blobBytes));
  ipcMain.handle('kwphoto:cache:list-records', (_event, params: { scope?: string | null }) => {
    return listCacheRecords(params.scope ?? undefined);
  });
  ipcMain.handle('kwphoto:cache:inspect', inspectCache);
  ipcMain.handle('kwphoto:cache:delete-folder', (_event, params: { folderScopeKey: string }) => {
    return deleteCacheRecords((record) => record.folderScopeKey === params.folderScopeKey);
  });
  ipcMain.handle('kwphoto:cache:clear', (_event, params: { scope?: string | null }) => {
    return deleteCacheRecords((record) => !params.scope || record.scope === params.scope);
  });
  ipcMain.handle('kwphoto:cache:clear-unused', clearUnusedCachePayloads);
  ipcMain.handle('kwphoto:cache:clear-all', clearEntireCacheStorage);
};

/**
 * Returns app-data paths used by the Electron cache backend.
 */
const getCacheStorageInfo = async () => {
  const rootDir = getCacheRootDir();
  const blobsDir = getCacheBlobsDir();

  await mkdir(blobsDir, { recursive: true });

  return {
    blobsDir,
    indexPath: getCacheIndexPath(),
    rootDir,
  };
};

/**
 * Fetches media in the main process so renderer CORS restrictions do not block caching.
 */
const fetchMediaBytes = async (url: string) => {
  const response = await fetch(url);

  if (!response.ok) {
    throw new Error(`Media request failed: ${response.status}`);
  }

  return {
    blobBytes: Array.from(new Uint8Array(await response.arrayBuffer())),
    contentType: response.headers.get('content-type') || undefined,
    statusCode: response.status,
  };
};

/**
 * Reads one cache record and its blob bytes when present.
 */
const readCacheRecord = async (key: string) => {
  const index = await readCacheIndex();
  const record = index.records.find((item) => item.key === key);

  if (!record) {
    return {};
  }

  if (!record.blobFileName) {
    return { record };
  }

  try {
    const blobBytes = Array.from(await readFile(path.join(getCacheBlobsDir(), record.blobFileName)));

    return { blobBytes, record };
  } catch {
    return { record: { ...record, hasBlob: false } };
  }
};

/**
 * Writes one metadata record and optional blob into the app-data cache.
 */
const writeCacheRecord = async (record: CacheRecord, blobBytes: number[] | null): Promise<void> => {
  await getCacheStorageInfo();

  const index = await readCacheIndex();
  const current = index.records.find((item) => item.key === record.key);
  const nextRecord: CacheRecord = { ...record };

  if (blobBytes) {
    const blobFileName = current?.blobFileName ?? createBlobFileName(record.key);

    await writeFile(path.join(getCacheBlobsDir(), blobFileName), Buffer.from(blobBytes));
    nextRecord.blobFileName = blobFileName;
    nextRecord.hasBlob = true;
  } else if (current?.blobFileName) {
    await rm(path.join(getCacheBlobsDir(), current.blobFileName), { force: true });
  }

  index.records = [
    ...index.records.filter((item) => item.key !== record.key),
    nextRecord,
  ];
  await writeCacheIndex(index);
};

/**
 * Lists cache records, optionally scoped to one workspace.
 */
const listCacheRecords = async (scope?: string): Promise<CacheRecord[]> => {
  const index = await readCacheIndex();

  return scope ? index.records.filter((record) => record.scope === scope) : index.records;
};

/**
 * Inspects indexed records and blob files so the renderer can display useful and orphaned cache sizes.
 */
const inspectCache = async () => {
  const inspection = await inspectCacheStorage();

  return {
    records: inspection.records,
    unusedCount: inspection.unusedBlobFiles.length,
    unusedSize: inspection.unusedBlobFiles.reduce((total, file) => total + file.size, 0),
  };
};

/**
 * Deletes cache records matching the given predicate and removes their blob files.
 */
const deleteCacheRecords = async (predicate: (record: CacheRecord) => boolean): Promise<void> => {
  const index = await readCacheIndex();
  const removedRecords = index.records.filter(predicate);

  await Promise.all(
    removedRecords.map((record) => (
      record.blobFileName
        ? rm(path.join(getCacheBlobsDir(), record.blobFileName), { force: true })
        : Promise.resolve()
    )),
  );

  index.records = index.records.filter((record) => !predicate(record));
  await writeCacheIndex(index);
};

/**
 * Removes blob files that no cache index entry can reach, and drops metadata for missing blobs.
 */
const clearUnusedCachePayloads = async (): Promise<void> => {
  const inspection = await inspectCacheStorage();
  const staleRecordKeys = new Set(
    inspection.records
      .filter((record) => record.blobFileName && record.hasBlob === false)
      .map((record) => record.key),
  );

  await Promise.all(
    inspection.unusedBlobFiles.map((file) => rm(path.join(getCacheBlobsDir(), file.fileName), { force: true })),
  );

  if (staleRecordKeys.size > 0) {
    await writeCacheIndex({
      records: inspection.records.filter((record) => !staleRecordKeys.has(record.key)),
    });
  }
};

/**
 * Removes the complete desktop cache root, including indexed records and orphaned blob files.
 */
const clearEntireCacheStorage = async (): Promise<void> => {
  await rm(getCacheRootDir(), { force: true, recursive: true });
  await mkdir(getCacheBlobsDir(), { recursive: true });
  await writeCacheIndex({ records: [] });
};

/**
 * Reads all blob files and annotates records whose payload disappeared from disk.
 */
const inspectCacheStorage = async (): Promise<{ records: CacheRecord[]; unusedBlobFiles: CacheBlobFile[] }> => {
  await getCacheStorageInfo();

  const index = await readCacheIndex();
  const blobFiles = await listCacheBlobFiles();
  const blobFileNames = new Set(blobFiles.map((file) => file.fileName));
  const referencedBlobFileNames = new Set(
    index.records
      .map((record) => record.blobFileName)
      .filter((fileName): fileName is string => Boolean(fileName)),
  );

  return {
    records: index.records.map((record) => (
      record.blobFileName
        ? { ...record, hasBlob: blobFileNames.has(record.blobFileName) }
        : record
    )),
    unusedBlobFiles: blobFiles.filter((file) => !referencedBlobFileNames.has(file.fileName)),
  };
};

const listCacheBlobFiles = async (): Promise<CacheBlobFile[]> => {
  try {
    const entries = await readdir(getCacheBlobsDir(), { withFileTypes: true });
    const files = entries.filter((entry) => entry.isFile());

    return Promise.all(
      files.map(async (entry) => {
        const fileStat = await stat(path.join(getCacheBlobsDir(), entry.name));

        return {
          fileName: entry.name,
          size: fileStat.size,
        };
      }),
    );
  } catch {
    return [];
  }
};

/**
 * Loads the JSON cache index, returning an empty index for first run.
 */
const readCacheIndex = async (): Promise<CacheIndex> => {
  try {
    const content = await readFile(getCacheIndexPath(), 'utf8');
    const parsed = JSON.parse(content) as CacheIndex;

    return {
      records: Array.isArray(parsed.records) ? parsed.records : [],
    };
  } catch {
    return { records: [] };
  }
};

/**
 * Persists the cache index atomically enough for the single-window desktop app.
 */
const writeCacheIndex = async (index: CacheIndex): Promise<void> => {
  await mkdir(getCacheRootDir(), { recursive: true });
  await writeFile(getCacheIndexPath(), JSON.stringify(index), 'utf8');
};

const getCacheRootDir = (): string => path.join(app.getPath('userData'), 'local-cache');

const getCacheBlobsDir = (): string => path.join(getCacheRootDir(), 'blobs');

const getCacheIndexPath = (): string => path.join(getCacheRootDir(), 'index.json');

const createBlobFileName = (key: string): string => {
  return `${createHash('sha256').update(key).digest('hex')}.bin`;
};

registerIpcHandlers();

void app.whenReady().then(async () => {
  await createMainWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      void createMainWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
