import { StyleSheet } from 'react-native';

import { MOBILE_SAGE_NEUTRALS, MOBILE_SAGE_SHADOWS, MOBILE_SAGE_SLATE } from '../mobile-theme';
import { FOLDER_GRID_GAP } from './folderConstants';

export const styles = StyleSheet.create({
  content: {
    alignItems: "stretch",
    gap: 10,
    paddingBottom: 84,
    paddingHorizontal: 14,
    paddingTop: 14,
    width: "100%",
  },
  configHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
  },
  configHeaderCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  configHeaderIcon: {
    alignItems: "center",
    borderRadius: 14,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  configCloseButton: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  configLabel: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 12,
    fontWeight: "900",
  },
  configIconGrid: {
    flexDirection: "row",
    gap: 7,
  },
  configIconOption: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 10,
  },
  configIconOptionCopy: {
    flex: 1,
    gap: 1,
    minWidth: 0,
  },
  configIconOptionMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 9,
    fontWeight: "800",
  },
  configIconOptionTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 12,
    fontWeight: "900",
  },
  configControlPanel: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    padding: 10,
  },
  configOptionPill: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    flexBasis: "30%",
    flexGrow: 1,
    flexDirection: "row",
    gap: 5,
    minHeight: 31,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  configOptionText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 11,
    fontWeight: "900",
  },
  configOverlay: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.sheetOverlay,
    flex: 1,
    justifyContent: "flex-end",
  },
  configPanelTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  configPanelTitleMain: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
  },
  configQuickButton: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 9,
    minHeight: 50,
    padding: 10,
  },
  configQuickCopy: {
    flex: 1,
    gap: 1,
    minWidth: 0,
  },
  configQuickGrid: {
    flexDirection: "row",
    gap: 7,
  },
  configQuickIcon: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.controlActive,
    borderRadius: 13,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  configQuickMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: "800",
  },
  configQuickTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 13,
    fontWeight: "900",
  },
  configSheet: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: "rgba(255, 255, 255, 0.76)",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderWidth: 1,
    gap: 9,
    padding: 14,
    paddingBottom: 18,
  },
  configSheetHandle: {
    alignSelf: "center",
    backgroundColor: MOBILE_SAGE_SLATE.ghost,
    borderRadius: 999,
    height: 4,
    width: 42,
  },
  configSummaryText: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 11,
    fontWeight: "900",
  },
  configSortGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  configTinyMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: "900",
  },
  configTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 16,
    fontWeight: "900",
  },
  disabledButton: {
    opacity: 0.44,
  },
  emptyText: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 13,
    fontWeight: "700",
    paddingVertical: 10,
  },
  error: {
    backgroundColor: "#fef2f2",
    borderColor: "#fecaca",
    borderRadius: 14,
    borderWidth: 1,
    color: "#b91c1c",
    fontSize: 13,
    fontWeight: "700",
    padding: 12,
  },
  dialog: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    padding: 16,
    width: "100%",
  },
  dialogActions: {
    flexDirection: "row",
    gap: 10,
  },
  dialogDescription: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
  dialogError: {
    color: "#b91c1c",
    fontSize: 12,
    fontWeight: "800",
  },
  dialogInput: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 13,
  },
  dialogOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.22)",
    flex: 1,
    justifyContent: "center",
    padding: 18,
  },
  dialogBottomOverlay: {
    backgroundColor: "rgba(15, 23, 42, 0.22)",
    justifyContent: "flex-end",
    paddingHorizontal: 18,
  },
  dialogPrimaryButton: {
    alignItems: "center",
    backgroundColor: "#10b981",
    borderRadius: 14,
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  dialogPrimaryText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "900",
  },
  dialogSecondaryButton: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minHeight: 44,
    justifyContent: "center",
  },
  dialogSecondaryText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 13,
    fontWeight: "900",
  },
  dialogTitle: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 18,
    fontWeight: "900",
  },
  dialogEmptyText: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 13,
    borderWidth: 1,
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 13,
    fontWeight: "800",
    padding: 14,
    textAlign: "center",
  },
  dialogLarge: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    maxHeight: "86%",
    padding: 16,
    width: "100%",
  },
  dialogLoadingLine: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    paddingVertical: 8,
  },
  dialogLoadingText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  dialogMetaText: {
    color: MOBILE_SAGE_SLATE.muted,
    flex: 1,
    fontSize: 12,
    fontWeight: "900",
    textAlign: "right",
  },
  dialogScroll: {
    maxHeight: 330,
  },
  dialogToolbarRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  fileCard: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 13,
    borderWidth: 1,
    flexBasis: "31%",
    flexGrow: 1,
    gap: 7,
    maxWidth: "32%",
    padding: 7,
    position: "relative",
  },
  fileCardBody: {
    gap: 2,
    minWidth: 0,
  },
  fileCardList: {
    alignItems: "center",
    flexBasis: "100%",
    flexDirection: "row",
    maxWidth: "100%",
  },
  waterfallFileCard: {
    flexBasis: "auto",
    flexGrow: 0,
    maxWidth: "100%",
    width: "100%",
  },
  mediaFileCard: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderWidth: 0,
    gap: 0,
    padding: 0,
  },
  mediaMasonryItem: {
    paddingBottom: 6,
    paddingHorizontal: 3,
  },
  largeFileCard: {
    borderRadius: 16,
    flexBasis: "100%",
    gap: 9,
    maxWidth: "100%",
    padding: 9,
  },
  largeFileCardTitle: {
    fontSize: 13,
    lineHeight: 17,
  },
  largeListFileCardFrame: {
    gap: 12,
    minHeight: 92,
    padding: 10,
  },
  mediumFileCard: {
    borderRadius: 14,
    flexBasis: "48%",
    gap: 8,
    maxWidth: "49%",
    padding: 8,
  },
  mediumListFileCardFrame: {
    gap: 10,
    minHeight: 76,
    padding: 8,
  },
  smallFileCard: {
    borderRadius: 13,
    flexBasis: "31%",
    gap: 6,
    maxWidth: "32%",
    padding: 6,
  },
  smallListFileCardFrame: {
    gap: 8,
    minHeight: 60,
    padding: 7,
  },
  fileCardMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: "700",
  },
  fileCardTitle: {
    color: MOBILE_SAGE_SLATE.title,
    fontSize: 12,
    fontWeight: "900",
  },
  fileGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  fileGroup: {
    gap: 8,
  },
  fileGroupTitle: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 13,
    fontWeight: "900",
  },
  fileList: {
    gap: 8,
  },
  mediaWaterfall: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 6,
  },
  mediaWaterfallColumn: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  fileThumb: {
    aspectRatio: 1,
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  mediaFileThumb: {
    width: "100%",
  },
  fileThumbFallback: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.controlActive,
    flex: 1,
    justifyContent: "center",
  },
  fileThumbFallbackText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: "900",
  },
  fileThumbImage: {
    height: "100%",
    width: "100%",
  },
  fileThumbList: {
    flex: 0,
    height: 58,
    width: 74,
  },
  folderFab: {
    alignItems: "center",
    bottom: 16,
    gap: 8,
    position: "absolute",
    right: 14,
    zIndex: 12,
  },
  folderFabMain: {
    alignItems: "center",
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  folderFabMainText: {
    fontSize: 30,
    fontWeight: "900",
    lineHeight: 34,
  },
  folderFabMenu: {
    alignItems: "center",
    gap: 8,
  },
  folderFabMenuButton: {
    ...MOBILE_SAGE_SHADOWS.floating,
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  largeListFileThumb: {
    height: 74,
    width: 94,
  },
  mediumListFileThumb: {
    height: 58,
    width: 74,
  },
  smallListFileThumb: {
    height: 46,
    width: 58,
  },
  coverPickerCard: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 13,
    borderWidth: 1,
    flexBasis: "31%",
    gap: 7,
    maxWidth: "32%",
    padding: 7,
    position: "relative",
  },
  coverPickerCardSelected: {
    borderColor: "#0f766e",
    borderWidth: 2,
  },
  coverPickerCheck: {
    backgroundColor: "#0f766e",
    borderRadius: 999,
    color: "#fff",
    fontSize: 11,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 6,
    paddingVertical: 3,
    position: "absolute",
    right: 5,
    top: 5,
  },
  coverPickerFolderCard: {
    justifyContent: "space-between",
  },
  coverPickerFolderIcon: {
    alignItems: "center",
    aspectRatio: 1,
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderRadius: 12,
    justifyContent: "center",
    width: "100%",
  },
  coverPickerFolderIconText: {
    color: "#0f766e",
    fontSize: 17,
    fontWeight: "900",
  },
  coverPickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    paddingBottom: 4,
  },
  coverPickerImage: {
    height: "100%",
    width: "100%",
  },
  coverPickerName: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 11,
    fontWeight: "900",
  },
  coverPickerThumb: {
    aspectRatio: 1,
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderRadius: 12,
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  coverDialogLarge: {
    maxHeight: "88%",
    maxWidth: 520,
  },
  folderCard: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 13,
    borderWidth: 1,
    gap: 7,
    padding: 7,
    position: "relative",
  },
  folderCardPlaceholder: {
    opacity: 0,
  },
  folderActionMenuButton: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderColor: "transparent",
    borderWidth: 1,
    borderRadius: 999,
    flexDirection: "row",
    gap: 5,
    height: 30,
    justifyContent: "center",
    paddingHorizontal: 8,
    width: "100%",
  },
  folderActionMenuText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 11,
    fontWeight: "900",
  },
  folderActionSheet: {
    ...MOBILE_SAGE_SHADOWS.floating,
    backgroundColor: "rgba(255, 255, 255, 0.98)",
    borderColor: "rgba(226, 232, 240, 0.96)",
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    marginHorizontal: 20,
    padding: 10,
    width: "86%",
  },
  folderActionSheetButton: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  folderActionSheetButtonText: {
    color: MOBILE_SAGE_SLATE.title,
    fontSize: 14,
    fontWeight: "900",
  },
  folderActionSheetClose: {
    alignItems: "center",
    borderRadius: 999,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  folderActionSheetHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    paddingLeft: 4,
  },
  folderActionSheetIcon: {
    alignItems: "center",
    borderRadius: 12,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  folderActionSheetOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.18)",
    flex: 1,
    justifyContent: "center",
  },
  folderActionSheetTitle: {
    color: MOBILE_SAGE_SLATE.title,
    flex: 1,
    fontSize: 14,
    fontWeight: "900",
  },
  folderActionsMenu: {
    alignSelf: "flex-end",
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 12,
    borderWidth: 1,
    gap: 5,
    padding: 6,
    position: "absolute",
    right: 0,
    shadowColor: "#0f172a",
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 20,
    top: 30,
    width: 132,
    zIndex: 8,
  },
  folderActionsToggle: {
    alignItems: "center",
    borderRadius: 999,
    height: 24,
    justifyContent: "center",
    marginLeft: "auto",
    width: 24,
  },
  folderActionsToggleActive: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
  },
  folderActionsToggleText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 18,
  },
  folderCardBody: {
    flex: 1,
    gap: 4,
    minWidth: 0,
    position: "relative",
  },
  folderCardPath: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: "700",
  },
  folderCardTitle: {
    color: MOBILE_SAGE_SLATE.title,
    fontSize: 12,
    fontWeight: "900",
  },
  largeFolderCardPath: {
    fontSize: 11,
    lineHeight: 16,
  },
  largeFolderCardTitle: {
    fontSize: 14,
    lineHeight: 18,
  },
  smallFolderCardTitle: {
    fontSize: 11,
  },
  folderCount: {
    backgroundColor: "rgba(15, 23, 42, 0.54)",
    borderRadius: 999,
    bottom: 6,
    color: "#fff",
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 6,
    paddingVertical: 2,
    position: "absolute",
    right: 6,
    zIndex: 2,
  },
  folderCover: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderRadius: 12,
    justifyContent: "center",
    minHeight: 104,
    overflow: "hidden",
    position: "relative",
  },
  folderCoverIcon: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.24)",
    borderColor: "rgba(255, 255, 255, 0.34)",
    borderRadius: 16,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    overflow: "hidden",
    width: 48,
    zIndex: 2,
  },
  largeFolderCoverIcon: {
    borderRadius: 18,
    height: 58,
    width: 58,
  },
  largeListFolderCoverIcon: {
    borderRadius: 13,
    height: 40,
    width: 40,
  },
  listFolderCoverIcon: {
    borderRadius: 11,
    height: 34,
    width: 34,
  },
  smallFolderCoverIcon: {
    borderRadius: 14,
    height: 40,
    width: 40,
  },
  smallListFolderCoverIcon: {
    borderRadius: 10,
    height: 28,
    width: 28,
  },
  folderCoverImage: {
    height: "50%",
    width: "50%",
  },
  folderCoverImageDouble: {
    height: "100%",
    width: "50%",
  },
  folderCoverImageFull: {
    height: "100%",
    width: "100%",
  },
  folderCoverImageTriplePrimary: {
    height: "50%",
    width: "100%",
  },
  folderCoverImages: {
    bottom: 0,
    flexDirection: "row",
    flexWrap: "wrap",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  folderGrid: {
    gap: FOLDER_GRID_GAP,
  },
  folderGridMeasure: {
    alignItems: "center",
    alignSelf: "stretch",
    marginBottom: 8,
    width: "100%",
  },
  folderHeadingSection: {
    marginBottom: 4,
  },
  folderHomeFrame: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.pageBg,
    flex: 1,
  },
  folderRestoreOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: MOBILE_SAGE_NEUTRALS.pageBg,
    elevation: 20,
    justifyContent: "center",
    zIndex: 20,
  },
  folderGridRow: {
    columnGap: FOLDER_GRID_GAP,
    flexDirection: "row",
    width: "100%",
  },
  folderListGrid: {
    justifyContent: "flex-start",
  },
  folderGridTrack: {
    justifyContent: "flex-start",
  },
  folderMeta: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    width: "100%",
  },
  folderMetaInline: {
    flex: 1,
    minWidth: 0,
    width: undefined,
  },
  folderMetaPill: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderRadius: 999,
    flexDirection: "row",
    gap: 3,
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  folderMetaPillText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 10,
    fontWeight: "900",
    lineHeight: 12,
  },
  folderStatusLine: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    justifyContent: "space-between",
  },
  folderStatusMain: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    minWidth: 0,
  },
  hint: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  pathPill: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    maxWidth: 150,
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  pathPillCompact: {
    maxWidth: 92,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  pathPillClickable: {
    backgroundColor: "#ecfdf5",
    borderColor: "#99f6e4",
  },
  pathPillRow: {
    flexDirection: "row",
    gap: 6,
  },
  pathPillRowCompact: {
    gap: 3,
  },
  pathPillScroll: {
    flex: 1,
  },
  pathPillScrollCompact: {
    maxHeight: 24,
  },
  pathPillText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 11,
    fontWeight: "900",
  },
  pathPillTextCompact: {
    fontSize: 10,
    lineHeight: 13,
  },
  largeFolderCard: {
    borderRadius: 17,
    flexBasis: "100%",
    gap: 9,
    maxWidth: "100%",
    padding: 9,
  },
  largeFolderCover: {
    borderRadius: 15,
    minHeight: 164,
  },
  listFolderCard: {
    alignItems: "flex-start",
    flexBasis: "100%",
    flexDirection: "row",
    gap: 8,
    maxWidth: "100%",
  },
  listFolderCover: {
    flex: 0,
    height: 64,
    minHeight: 64,
    width: 82,
  },
  largeListFolderCardFrame: {
    gap: 12,
    minHeight: 112,
    padding: 12,
  },
  largeListFolderCover: {
    borderRadius: 15,
    height: 92,
    minHeight: 92,
    width: 118,
  },
  mediumListFolderCardFrame: {
    gap: 10,
    minHeight: 88,
    padding: 10,
  },
  mediumListFolderCover: {
    borderRadius: 13,
    height: 70,
    minHeight: 70,
    width: 90,
  },
  smallListFolderCardFrame: {
    gap: 8,
    minHeight: 70,
    padding: 8,
  },
  smallListFolderCover: {
    borderRadius: 12,
    height: 54,
    minHeight: 54,
    width: 66,
  },
  mediumFolderCard: {
    borderRadius: 15,
    flexBasis: "48%",
    gap: 8,
    maxWidth: "49%",
    padding: 8,
  },
  mediumFolderCover: {
    borderRadius: 13,
    minHeight: 108,
  },
  message: {
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    borderRadius: 14,
    borderWidth: 1,
    color: "#0f766e",
    fontSize: 13,
    fontWeight: "800",
    padding: 12,
  },
  moveFolderCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  moveFolderIcon: {
    color: "#0f766e",
    fontSize: 19,
    fontWeight: "900",
  },
  moveFolderList: {
    gap: 8,
    paddingBottom: 4,
  },
  moveFolderMain: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 9,
    minWidth: 0,
  },
  moveFolderMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: "800",
  },
  moveFolderName: {
    color: MOBILE_SAGE_SLATE.title,
    fontSize: 13,
    fontWeight: "900",
  },
  moveFolderRow: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    padding: 10,
  },
  moveTargetButton: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderRadius: 999,
    height: 30,
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  moveTargetButtonText: {
    color: "#0f766e",
    fontSize: 11,
    fontWeight: "900",
  },
  moveTargetLabel: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: "900",
  },
  moveTargetPanel: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 13,
    borderWidth: 1,
    gap: 2,
    padding: 10,
  },
  moveTargetValue: {
    color: MOBILE_SAGE_SLATE.strong,
    fontSize: 13,
    fontWeight: "900",
  },
  nativeVideoCloseButton: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.52)",
    borderColor: "rgba(255, 255, 255, 0.16)",
    borderRadius: 999,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    position: "absolute",
    width: 44,
    zIndex: 3,
  },
  nativeVideoCloseButtonSide: {
    right: 16,
    top: "50%",
    transform: [{ translateY: -22 }],
  },
  nativeVideoPlayer: {
    flex: 1,
    width: "100%",
  },
  nativeVideoPlayerHidden: {
    opacity: 0,
  },
  nativeVideoPlayerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000",
  },
  nativeVideoPlayerOverlayPreparing: {
    backgroundColor: "transparent",
  },
  nativeVideoPlayerOverlayIdle: {
    backgroundColor: "transparent",
  },
  nativeVideoPosterImage: {
    height: "100%",
    width: "100%",
  },
  nativeVideoPosterImageOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  nativeVideoPosterLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  nativeVideoSourceBadge: {
    backgroundColor: "rgba(15, 23, 42, 0.48)",
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: 999,
    borderWidth: 1,
    left: 16,
    paddingHorizontal: 8,
    paddingVertical: 4,
    position: "absolute",
    zIndex: 3,
  },
  nativeVideoSourceBadgeText: {
    color: "rgba(255, 255, 255, 0.68)",
    fontSize: 10,
    fontWeight: "800",
  },
  nativeVideoLoadingLayer: {
    alignItems: "center",
    gap: 10,
    justifyContent: "center",
    ...StyleSheet.absoluteFillObject,
  },
  nativeVideoLoadingText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "900",
  },
  overwriteButton: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    flex: 1,
    minHeight: 32,
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  overwriteButtonActive: {
    backgroundColor: "#0f766e",
    borderColor: "#0f766e",
  },
  overwriteButtonText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 11,
    fontWeight: "900",
  },
  overwriteButtonTextActive: {
    color: "#fff",
  },
  overwriteGroup: {
    flexDirection: "row",
    gap: 6,
  },
  pressedCard: {
    transform: [{ translateY: 1 }],
  },
  previewAlbumClose: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderRadius: 999,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  previewAlbumDialog: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
    maxHeight: "78%",
    padding: 14,
    width: "100%",
  },
  previewAlbumHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  previewAlbumList: {
    maxHeight: 360,
  },
  previewAlbumRow: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    marginBottom: 8,
    padding: 10,
  },
  previewAlbumRowActive: {
    backgroundColor: "#ecfdf5",
    borderColor: "#99f6e4",
  },
  previewAlbumRowCopy: {
    flex: 1,
    minWidth: 0,
  },
  previewAlbumRowIcon: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderRadius: 999,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  previewAlbumRowIconActive: {
    backgroundColor: "#16b741",
  },
  previewAlbumRowMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
  },
  previewAlbumRowTitle: {
    color: MOBILE_SAGE_SLATE.title,
    fontSize: 13,
    fontWeight: "900",
  },
  previewBackButton: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    borderColor: "rgba(226, 232, 240, 0.86)",
    borderRadius: 999,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
    ...MOBILE_SAGE_SHADOWS.panel,
  },
  previewCloseButton: {
    backgroundColor: "rgba(255, 255, 255, 0.16)",
    borderColor: "rgba(255, 255, 255, 0.28)",
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  previewCloseText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "900",
  },
  previewChromeLayer: {
    width: "100%",
  },
  previewFallback: {
    alignItems: "center",
    flex: 1,
    gap: 8,
    justifyContent: "center",
    padding: 28,
  },
  previewFallbackText: {
    color: "#94a3b8",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  previewFallbackTitle: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "900",
  },
  previewExternalPlayerInfuseIcon: {
    borderColor: "rgba(255, 255, 255, 0.66)",
    borderRadius: 7,
    borderWidth: 1,
    height: 22,
    overflow: "hidden",
    width: 22,
  },
  previewHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    paddingBottom: 10,
    paddingHorizontal: 10,
    paddingTop: 8,
    zIndex: 8,
  },
  previewHeaderCopy: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  previewGestureLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 4,
  },
  previewImage: {
    flex: 1,
    width: "100%",
  },
  previewImageFooter: {
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    width: "100%",
  },
  previewImageHint: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "rgba(15, 23, 42, 0.68)",
    borderColor: "rgba(255, 255, 255, 0.16)",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 9,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  previewImageHintMeta: {
    color: "#cbd5e1",
    fontSize: 11,
    fontWeight: "800",
  },
  previewImageHintTitle: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "900",
  },
  previewPosterActionStack: {
    alignItems: "center",
    gap: 10,
    left: 0,
    position: "absolute",
    right: 0,
    top: "50%",
    transform: [{ translateY: -32 }],
    zIndex: 3,
  },
  previewPosterPlayButton: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.7)",
    borderColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 999,
    borderWidth: 1,
    height: 64,
    justifyContent: "center",
    width: 64,
  },
  previewPosterPlayButtonLoading: {
    opacity: 0.82,
  },
  previewSourceBadge: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "rgba(15, 23, 42, 0.62)",
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  previewSourceBadgeText: {
    color: "#e2e8f0",
    fontSize: 11,
    fontWeight: "900",
  },
  previewImageLayer: {
    ...StyleSheet.absoluteFillObject,
    height: "100%",
    width: "100%",
  },
  previewImageLayerFallback: {
    alignItems: "center",
    gap: 8,
    justifyContent: "center",
    padding: 28,
  },
  previewImageLayerHidden: {
    opacity: 0,
  },
  previewImageLayerVisible: {
    opacity: 1,
  },
  previewProgressiveImage: {
    flex: 1,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  previewUpgradeBadge: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "rgba(15, 23, 42, 0.72)",
    borderColor: "rgba(255, 255, 255, 0.16)",
    borderRadius: 999,
    borderWidth: 1,
    bottom: 22,
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 12,
    paddingVertical: 8,
    position: "absolute",
  },
  previewUpgradeBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "900",
  },
  previewWarmupImage: {
    height: 1,
    width: 1,
  },
  previewWarmupLayer: {
    height: 1,
    left: 0,
    opacity: 0,
    overflow: "hidden",
    position: "absolute",
    top: 0,
    width: 1,
  },
  previewVideo: {
    flex: 1,
    width: "100%",
  },
  previewVideoPoster: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#020617",
  },
  previewVideoPosterImage: {
    height: "100%",
    width: "100%",
  },
  previewVideoShell: {
    flex: 1,
    position: "relative",
    width: "100%",
  },
  previewInfoFloatingLayer: {
    bottom: 90,
    left: 0,
    paddingHorizontal: 12,
    position: "absolute",
    right: 0,
    zIndex: 5,
  },
  previewMeta: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: "700",
  },
  previewNotice: {
    alignSelf: "center",
    backgroundColor: "rgba(15, 23, 42, 0.82)",
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 999,
    borderWidth: 1,
    marginTop: 4,
    paddingHorizontal: 14,
    paddingVertical: 8,
    zIndex: 9,
  },
  previewNoticeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "900",
  },
  previewOpenButton: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#0f766e",
    borderRadius: 999,
    minHeight: 38,
    justifyContent: "center",
    marginTop: 10,
    paddingHorizontal: 18,
  },
  previewOpenButtonText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "900",
  },
  previewOverlay: {
    backgroundColor: "#020617",
    flex: 1,
  },
  previewOriginalAction: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.94)",
    borderColor: "rgba(226, 232, 240, 0.86)",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    height: 36,
    justifyContent: "center",
    maxWidth: 122,
    minWidth: 0,
    paddingHorizontal: 10,
    ...MOBILE_SAGE_SHADOWS.panel,
  },
  previewOriginalActionText: {
    color: MOBILE_SAGE_SLATE.title,
    flexShrink: 1,
    fontSize: 12,
    fontWeight: "900",
  },
  previewStepButton: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  previewStepMeta: {
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "800",
  },
  previewStepText: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "700",
    lineHeight: 30,
  },
  previewStepper: {
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
    justifyContent: "center",
    padding: 18,
    zIndex: 6,
  },
  previewToolbar: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
    justifyContent: "flex-end",
    paddingRight: 2,
  },
  previewToolbarScroll: {
    flex: 1,
  },
  previewToolButtonDisabled: {
    opacity: 0.42,
  },
  previewTitle: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "900",
  },
  screen: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.pageBg,
    flex: 1,
    gap: 8,
  },
  section: {
    gap: 8,
    width: "100%",
  },
  sectionCount: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 12,
    fontWeight: "800",
  },
  sectionHeading: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  sectionHeadingRight: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 6,
    justifyContent: "flex-end",
    minWidth: 0,
  },
  sectionTitle: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 13,
    fontWeight: "900",
  },
  segmented: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.panel,
    borderColor: MOBILE_SAGE_NEUTRALS.border,
    borderRadius: 999,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    padding: 2,
  },
  segmentedItem: {
    alignItems: "center",
    borderRadius: 999,
    flex: 1,
    minHeight: 26,
    minWidth: 32,
    justifyContent: "center",
    paddingHorizontal: 7,
  },
  segmentedItemActive: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.controlActive,
  },
  segmentedText: {
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 10,
    fontWeight: "900",
  },
  segmentedTextActive: {
    color: MOBILE_SAGE_SLATE.strong,
  },
  selectedCard: {
    borderColor: "#0f766e",
    borderWidth: 2,
  },
  selectionActionButton: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderRadius: 999,
    flex: 1,
    height: 32,
    justifyContent: "center",
  },
  selectionActionText: {
    color: MOBILE_SAGE_SLATE.body,
    fontSize: 11,
    fontWeight: "900",
  },
  selectionActions: {
    flexDirection: "row",
    gap: 5,
  },
  selectionBar: {
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    borderColor: "#99f6e4",
    borderRadius: 13,
    borderWidth: 1,
    gap: 8,
    padding: 8,
  },
  selectionDangerButton: {
    alignItems: "center",
    backgroundColor: "#fef2f2",
    borderRadius: 999,
    flex: 1,
    height: 32,
    justifyContent: "center",
  },
  selectionDangerText: {
    color: "#b91c1c",
    fontSize: 11,
    fontWeight: "900",
  },
  selectionIconButton: {
    alignItems: "center",
    backgroundColor: MOBILE_SAGE_NEUTRALS.panelAlt,
    borderRadius: 999,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  selectionMeta: {
    color: MOBILE_SAGE_SLATE.subtle,
    fontSize: 10,
    fontWeight: "800",
  },
  selectionSummary: {
    gap: 1,
  },
  selectionTitle: {
    color: MOBILE_SAGE_SLATE.title,
    fontSize: 12,
    fontWeight: "900",
  },
  selectionToggle: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderColor: "#cbd5e1",
    borderRadius: 999,
    borderWidth: 1,
    height: 24,
    justifyContent: "center",
    left: 7,
    position: "absolute",
    top: 7,
    width: 24,
    zIndex: 6,
  },
  selectionToggleSelected: {
    backgroundColor: "#0f766e",
    borderColor: "#0f766e",
  },
  selectionToggleText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "900",
  },
  smallFolderCard: {
    borderRadius: 13,
    flexBasis: "31%",
    gap: 6,
    maxWidth: "32%",
    padding: 6,
  },
  smallFolderCover: {
    borderRadius: 11,
    minHeight: 72,
  },
  smallFolderCount: {
    bottom: 5,
    fontSize: 9,
    paddingHorizontal: 5,
    right: 5,
  },
  smallFolderActionsToggle: {
    height: 22,
    width: 22,
  },
  smallFolderMeta: {
    flexWrap: "nowrap",
    gap: 3,
  },
  smallFolderMetaPill: {
    flexShrink: 0,
    gap: 1,
    paddingHorizontal: 4,
    paddingVertical: 3,
  },
  smallFolderMetaPillText: {
    fontSize: 9,
    lineHeight: 11,
  },
  smallFolderStatusLine: {
    gap: 4,
  },
  tag: {
    backgroundColor: MOBILE_SAGE_NEUTRALS.control,
    borderRadius: 999,
    color: MOBILE_SAGE_SLATE.muted,
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  themeTag: {
    backgroundColor: "#ecfdf5",
    color: "#0f766e",
  },
  videoBadge: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.66)",
    borderRadius: 999,
    color: "#fff",
    fontSize: 10,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 7,
    paddingVertical: 3,
    position: "absolute",
    right: 6,
    top: 6,
  },
});
